version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: cosmic-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-changeme}
      MONGO_INITDB_DATABASE: cosmic-insights
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - cosmic-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/cosmic-insights --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: cosmic-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-changeme}@mongodb:27017/cosmic-insights?authSource=admin
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-dev_access_secret_change_in_production}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-dev_refresh_secret_change_in_production}
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      CSRF_SECRET: ${CSRF_SECRET:-dev_csrf_secret_change_in_production}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-dev_encryption_key_32_chars_12}
      COOKIE_SECRET: ${COOKIE_SECRET:-dev_cookie_secret_change_in_prod}
      CORS_ORIGIN: http://localhost:3000
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      CLIENT_URL: http://localhost:3000
      ADMIN_EMAILS: admin@cosmicinsights.com
      LOG_LEVEL: debug
      ANALYTICS_RETENTION_DAYS: 90
      MAX_FILE_SIZE: 5242880
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/logs:/app/logs
      - backend_node_modules:/app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - cosmic-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB Express (Web GUI for MongoDB)
  mongo-express:
    image: mongo-express:1.0
    container_name: cosmic-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-changeme}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-changeme}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-pass}
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - cosmic-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  backend_node_modules:
    driver: local

networks:
  cosmic-network:
    driver: bridge
