# Generated by Django 4.2.7 on 2025-10-15 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='API endpoint path (e.g., /api/auth/login)', max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('users', 'User Management'), ('analytics', 'Analytics'), ('ml', 'Machine Learning'), ('admin', 'Administration'), ('other', 'Other')], default='other', max_length=50)),
                ('name', models.CharField(help_text='Human-readable endpoint name', max_length=255)),
                ('description', models.TextField(help_text='What this endpoint does')),
                ('request_schema', models.JSONField(default=dict, help_text='Expected request body schema')),
                ('response_schema', models.JSONField(default=dict, help_text='Expected response schema')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Public (no auth required) endpoint')),
                ('requires_admin', models.BooleanField(default=False)),
                ('rate_limit', models.IntegerField(default=100, help_text='Requests per minute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Endpoint',
                'verbose_name_plural': 'API Endpoints',
                'db_table': 'api_endpoints',
                'ordering': ['category', 'path'],
                'unique_together': {('path', 'method')},
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this API key', max_length=255)),
                ('key_hash', models.CharField(help_text='SHA-256 hash of the API key', max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 characters of the key for identification', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('allowed_endpoints', models.JSONField(default=list, help_text='List of allowed endpoint patterns')),
                ('rate_limit', models.IntegerField(default=1000, help_text='Requests per hour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date (null = never expires)', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error_message', models.TextField(blank=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api_management.apikey')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api_management.apiendpoint')),
            ],
            options={
                'verbose_name': 'API Usage Log',
                'verbose_name_plural': 'API Usage Logs',
                'db_table': 'api_usage_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'status_code'], name='api_usage_l_timesta_528a2d_idx'), models.Index(fields=['api_key', 'timestamp'], name='api_usage_l_api_key_357aef_idx')],
            },
        ),
    ]
