# Generated by Django 4.2.7 on 2025-10-12 11:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('project_id', models.CharField(default='default', max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('mongo_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('qdrant_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('document_type', models.CharField(default='journal_entry', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('project_id', models.CharField(max_length=100)),
                ('experiment_type', models.CharField(choices=[('embedding', 'Embedding Generation'), ('clustering', 'Pattern Clustering'), ('classification', 'Text Classification'), ('training', 'Model Training')], default='embedding', max_length=50)),
                ('dataset_ref', models.CharField(blank=True, max_length=500)),
                ('model_ref', models.CharField(blank=True, max_length=500)),
                ('config', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'experiments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector_id', models.CharField(max_length=100, unique=True)),
                ('model_name', models.CharField(max_length=200)),
                ('dimension', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='app.document')),
            ],
            options={
                'db_table': 'embeddings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user_id', 'document_type'], name='documents_user_id_588d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['embedding_status', 'created_at'], name='documents_embeddi_19e693_idx'),
        ),
    ]
